### ISSUE TITLE
java.awt.HeadlessException

### ISSUE THREAD

**Issue by Igetin** [Loreinator/Shuffle-Move#112]
Trying to run Shuffle Move on Fedora. When I launch the `.jar` file, I get an error:

```
[admin@localhost Shuffle Move]$ ./launch.sh
[Feb 24, 2016 6:05:14 PM] [FINE] config/paths.txt (No such file or directory)
[Feb 24, 2016 6:05:14 PM] [FINE] /home/admin/Shuffle-Move/config/icons.txt (No such file or directory)
[Feb 24, 2016 6:05:14 PM] [FINE] /home/admin/Shuffle-Move/config/preferences.txt (No such file or directory)
[Feb 24, 2016 6:05:25 PM] [SEVERE] Failure on start:
java.awt.HeadlessException
	at java.awt.GraphicsEnvironment.checkHeadless(GraphicsEnvironment.java:204)
	at java.awt.Window.<init>(Window.java:536)
	at java.awt.Frame.<init>(Frame.java:420)
	at java.awt.Frame.<init>(Frame.java:385)
	at javax.swing.JFrame.<init>(JFrame.java:189)
	at shuffle.fwk.gui.ShuffleFrame.<init>(ShuffleFrame.java:84)
	at shuffle.fwk.ShuffleController.loadFrame(ShuffleController.java:425)
	at shuffle.fwk.ShuffleController.<init>(ShuffleController.java:211)
	at shuffle.fwk.ShuffleController.main(ShuffleController.java:157)
Exception in thread "AWT-EventQueue-0" java.awt.HeadlessException
	at java.awt.GraphicsEnvironment.checkHeadless(GraphicsEnvironment.java:204)
	at java.awt.Window.<init>(Window.java:536)
	at java.awt.Frame.<init>(Frame.java:420)
	at java.awt.Frame.<init>(Frame.java:385)
	at javax.swing.JFrame.<init>(JFrame.java:189)
	at shuffle.fwk.gui.ShuffleFrame.<init>(ShuffleFrame.java:84)
	at shuffle.fwk.ShuffleController.getFrame(ShuffleController.java:418)
	at shuffle.fwk.ShuffleController$1.run(ShuffleController.java:161)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

Any help? I have the latest Java installed.

**Comment by Loreinator** [comment]
Try updating your Java version I guess? It works on Ubuntu, Macintosh,
Windows xp/7/8/10 so it's probably an issue with the Java version. 8u51
works the best, but it should work with any newer Java version after that.

-Andrew

**Comment by Igetin** [comment]
Like I said, I already have the latest Java version. `java -version` returns the version number 1.8.0_72.

**Comment by Loreinator** [comment]
I'm responding through email, so your edit was never sent to me.

Try looking up fedora compatibility with Java swing gui windows. I don't
have a fedora install at home and I'm on the train right now so searching
is cumbersome and slow.

-Andrew

**Comment by Igetin** [comment]
Hmm, it seems that the problem may not be in Fedora itself, but in OpenJDK which ships with Fedora. OpenJDK is known to sometimes have GUI problems. Going to install Oracle's JDK and see if it works after that.

**Comment by Loreinator** [comment]
Alright, good luck, I hope it works!

-Andrew

**Comment by Igetin** [comment]
OpenJDK was the problem indeed! Works fine on Oracle's JDK. Closing this issue.

**Comment by Loreinator** [comment]
Awesome! Thanks for reporting it, it's good to keep a record of known
problems.

-Andrew
