### ISSUE TITLE
StackOverflowError when entering team

### ISSUE THREAD

**Issue by svivian** [Loreinator/Shuffle-Move#126]
After a short while using Shuffle Move on Ubuntu 15.10, I get this error in the terminal:

```
Exception in thread "AWT-EventQueue-1" java.lang.StackOverflowError
	at java.awt.AWTEventMulticaster.componentMoved(AWTEventMulticaster.java:169)
	at java.awt.AWTEventMulticaster.componentMoved(AWTEventMulticaster.java:169)
	at java.awt.AWTEventMulticaster.componentMoved(AWTEventMulticaster.java:169)
	at java.awt.AWTEventMulticaster.componentMoved(AWTEventMulticaster.java:169)
	...etc
```

With that last line repeated at least 100 times. Can't really tell if there's any pattern to it. Basically I'm entering Pokemon into the grid in Express mode, pressing F5 to calculate a move, doing the move on my 3DS (but not in SM), then entering the new board still in Express mode.

[bugReport_20160423_230803_BST.zip](https://github.com/Loreinator/Shuffle-Move/files/233172/bugReport_20160423_230803_BST.zip)

**Comment by Loreinator** [comment]
Can you reproduce the bug? From the bug report I am unable to identify the problem. Please try running the program with this so it captures the entire console output to file, then include it in your zip if it happens again. Be sure to snap the bug report the moment that the problem occurs so I can attempt to replicate it in a development environment.

In regards to troubleshooting, try installing the Oracle Java 8 binary to avoid any compatibility problems.
